trigger:
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NuGetToolInstaller@1
      displayName: "Install NuGets"
      inputs:
        versionSpec: 6.6.1
        checkLatest: true

    - task: NuGetCommand@2
      displayName: "Restore NuGets"
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: "Build Solution"
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifacts"
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy_To_PROD
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  jobs:
  - job: Deploy
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download Artifacts'
      inputs:
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure App Service Deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'civiq-dev-ci-azureconnection'
        appType: 'webApp'
        WebAppName: 'juvvaltech-web-dev-ws-as'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/*.zip'
        enableCustomDeployment: true
        DeploymentType: 'webDeploy'